# Site info
title: Nickgismokato Blog
description: The blog of Nickgismokato


# Jekyll config
permalink: pretty
safe: false

kramdown:
  input: GFM


# Remote theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-hacker
